# Generated by Django 5.2.17 on 2026-09-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentprofile', '0002_alter_studentprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_status',
            field=models.CharField(default='Academic pending', max_length=20),
        ),
    ]
