# Generated by Django 6.0.7 on 2026-09-21 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companydetails', '0002_remove_company_ctc_remove_company_eligibility_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ctc', models.CharField(max_length=50)),
                ('openings', models.PositiveIntegerField(default=0)),
                ('eligibility', models.TextField()),
                ('process', models.TextField()),
                ('rounds', models.CharField(max_length=100)),
                ('drive_date', models.DateField()),
                ('last_date', models.DateField()),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Open', 'Open'), ('Closed', 'Closed')], default='Upcoming', max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_drives', to='companydetails.company')),
            ],
        ),
    ]
