# Generated by Django 5.2.17 on 2026-09-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.CharField(blank=True, max_length=50)),
                ('industry', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Hiring Now', 'Hiring Now'), ('Upcoming', 'Upcoming'), ('Closed', 'Closed')], default='Upcoming', max_length=30)),
                ('roles', models.CharField(max_length=300)),
                ('ctc', models.CharField(max_length=50)),
                ('openings', models.PositiveIntegerField(default=0)),
                ('website', models.URLField(blank=True)),
                ('about', models.TextField()),
                ('hq', models.CharField(max_length=100)),
                ('eligibility', models.TextField()),
                ('process', models.TextField()),
                ('rounds', models.CharField(max_length=50)),
            ],
        ),
    ]
