# Generated by Django 6.0.7 on 2026-09-20 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companydetails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='ctc',
        ),
        migrations.RemoveField(
            model_name='company',
            name='eligibility',
        ),
        migrations.RemoveField(
            model_name='company',
            name='openings',
        ),
        migrations.RemoveField(
            model_name='company',
            name='process',
        ),
        migrations.RemoveField(
            model_name='company',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='company',
            name='rounds',
        ),
        migrations.RemoveField(
            model_name='company',
            name='status',
        ),
    ]
